// <auto-generated />
using System;
using HotelProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelProject.Migrations
{
    [DbContext(typeof(SiteContext))]
    [Migration("20221227074705_iletisim")]
    partial class iletisim
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HotelProject.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sifre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("HotelProject.Models.Iletisim", b =>
                {
                    b.Property<int>("IletisimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Konu")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Mesaj")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Soyad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("IletisimId");

                    b.ToTable("Iletisims");
                });

            modelBuilder.Entity("HotelProject.Models.Musteri", b =>
                {
                    b.Property<int>("Idno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Act")
                        .HasColumnType("int");

                    b.Property<string>("Adisoyadi")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TcNo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telefon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Uyruk")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Idno");

                    b.ToTable("Musteris");
                });

            modelBuilder.Entity("HotelProject.Models.OdaOzellik", b =>
                {
                    b.Property<int>("Idno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Act")
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Ikon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Idno");

                    b.ToTable("OdaOzelliks");
                });

            modelBuilder.Entity("HotelProject.Models.OdaTip", b =>
                {
                    b.Property<int>("Idno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Act")
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Ozellikler")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Ucret")
                        .HasColumnType("double");

                    b.HasKey("Idno");

                    b.ToTable("OdaTips");
                });

            modelBuilder.Entity("HotelProject.Models.Odalar", b =>
                {
                    b.Property<int>("Idno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Act")
                        .HasColumnType("int");

                    b.Property<bool>("Anasayfa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cephe")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OdaAdi")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("OdaNo")
                        .HasColumnType("int");

                    b.Property<int>("OdaTip")
                        .HasColumnType("int");

                    b.Property<string>("Ozellikler")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("YatakSayisi")
                        .HasColumnType("int");

                    b.HasKey("Idno");

                    b.HasIndex("OdaTip");

                    b.ToTable("Odalars");
                });

            modelBuilder.Entity("HotelProject.Models.Pansiyonlar", b =>
                {
                    b.Property<int>("Idno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Act")
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Ucret")
                        .HasColumnType("double");

                    b.HasKey("Idno");

                    b.ToTable("Pansiyonlars");
                });

            modelBuilder.Entity("HotelProject.Models.Rezervasyon", b =>
                {
                    b.Property<int>("Idno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Act")
                        .HasColumnType("int");

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Cocuk")
                        .HasColumnType("int");

                    b.Property<double>("EkUcret")
                        .HasColumnType("double");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int?>("OdaId")
                        .HasColumnType("int");

                    b.Property<int>("OdaTipId")
                        .HasColumnType("int");

                    b.Property<int>("Pansiyon")
                        .HasColumnType("int");

                    b.Property<string>("RandomKey")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Ucret")
                        .HasColumnType("double");

                    b.Property<int>("Yetiskin")
                        .HasColumnType("int");

                    b.HasKey("Idno");

                    b.HasIndex("MusteriId");

                    b.HasIndex("OdaId");

                    b.HasIndex("OdaTipId");

                    b.HasIndex("Pansiyon");

                    b.ToTable("Rezervasyons");
                });

            modelBuilder.Entity("HotelProject.Models.Odalar", b =>
                {
                    b.HasOne("HotelProject.Models.OdaTip", "OdaTips")
                        .WithMany()
                        .HasForeignKey("OdaTip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelProject.Models.Rezervasyon", b =>
                {
                    b.HasOne("HotelProject.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelProject.Models.Odalar", "Odalar")
                        .WithMany()
                        .HasForeignKey("OdaId");

                    b.HasOne("HotelProject.Models.OdaTip", "OdaTip")
                        .WithMany()
                        .HasForeignKey("OdaTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelProject.Models.Pansiyonlar", "Pansiyonlars")
                        .WithMany()
                        .HasForeignKey("Pansiyon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
